# -*- coding: utf-8 -*-
"""Capstone 1_ML_ZoomCamp_2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qythwp1QKVRTGyEDkljQZVxjO6Zmk0sN

### CAPSTONE PROJECT 1

### LIBRARIES :
"""

import pandas as pd

"""### READ THE DATASET :"""

df = pd.read_csv('space_missions_dataset.csv')
df.head()

df.tail()

"""### DROPPING UNNECESSARY COLUMNS"""

def clean_data(df):
    df.drop(columns=['Mission ID', 'Launch Date', 'Target Name', 
                     'Fuel Consumption (tons)', 'Payload Weight (tons)', 
                     'Launch Vehicle'], inplace=True)
    return df

"""### OUTLIERS WERE DETECTED AND REMOVED BASED ON THE INTERQUARTILE RANGE (IQR) METHOD TO ENSURE ROBUST MODEL PERFORMANCE"""

def remove_outliers(df, column):
    q1 = df[column].quantile(0.25)
    q3 = df[column].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    return df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

if __name__ == "__main__":
    df = pd.read_csv('space_missions_dataset.csv')
    print("The data has been successfully loaded.")
    print(df.head())

    df = clean_data(df)
    print("The data has been successfully cleaned.")
    print(df.columns)

    df = remove_outliers(df, 'Mission Success (%)')
    print("Outliers successfully removed.")
    print(df.describe())


